### PR TITLE
Eye-Candy

### PR DESCRIPTION
**Pull request by schemhad**
New look, logo and external css-file.

### CODE REVIEW

**Comment by rojer** [comment]
screenshot?

**Comment by schemhad** [comment]
> screenshot?

Demo

**Comment by rojer** [comment]
ooh, shiny! well done!
what about values for uptime and paired/provisioned?

**Comment by schemhad** [comment]
Fixed a bug with Apple-System-Fonts on iOS 13.

**Comment by rojer** [comment]
very nice and seems to be working. thank you!

**Pull request merged**
