### PR TITLE
Addon unification / DHT support / addon as switch / plus addon support

### PR DESCRIPTION
**Pull request by markirb**
This unifies all addon sensor related Pull-requests with a Refactoring and also shoud enable https://github.com/mongoose-os-apps/shelly-homekit/issues/1102

it also adds plusI4 as requested in https://github.com/mongoose-os-apps/shelly-homekit/pull/1307

those are all the other commits:
https://github.com/mongoose-os-apps/shelly-homekit/pull/967 addon as switch
https://github.com/mongoose-os-apps/shelly-homekit/pull/1110 dht
https://github.com/mongoose-os-apps/shelly-homekit/pull/1307 plus addon

### CODE REVIEW

**Comment by markirb** [comment]
also: plus addon should work, according to
https://github.com/arendst/Tasmota/discussions/18885
we might need to use GPIO1 instead of GPIO0 (current code) but that is everything

**Comment by markirb** [comment]
@timoschilling can you review this please?

**Comment by hejsiri** [comment]
Does Addon and DHT22 sensor work in Shelly 2PM and beta5 ? It does not detect the sensor in me.

**Comment by markirb** [comment]
It should. Has it worked before. Does it work on original FW?

**Comment by hejsiri** [comment]
OK, I checked on the original software. Addon works correctly with the DHT22 sensor. It shows temprature and humidity. After upgrading back to shelly-homekit beta, the addon is not detected. It does not show the sensor in the webgui.

**Comment by markirb** [comment]
Mhh, you're not on latest beta5. I have reports it works there but:

If it still does not work then the standard mongoose DHT driver seems not to support your model. You can post your exact model, but I think right now I cannot do anything there currently.

**Comment by hejsiri** [comment]
@markirb It is Shelly 2PM.

**Comment by markirb** [comment]
I mean the model of you DHT

**Comment by hejsiri** [comment]
AM2302

**Comment by markirb** [comment]
Totally should work, at least I see no reason why not. Please post this problem as issue with all details. Maybe we find someone who has a similar issue and it can be worked out.

**Pull request merged**
