### PR TITLE
Version Check and GUI Update

### PR DESCRIPTION
**Pull request by schemhad**
* Adds a VersionCheck for major Releases over GitHub API
* Adds Favicon
* Dynamically sets Hostname as PageTitle
* Slightly GUI improvements

### CODE REVIEW

**Comment by rojer** [comment]
can you add screenshots / screencap of the process?

**Comment by schemhad** [comment]
image

**Comment by schemhad** [comment]
image

The function compares the latest tag_Name only from the releases-api with the local one.

**Comment by andyblac** [comment]
@schemhad could you the ability to update like we discussed in the ticket ?

**Comment by schemhad** [comment]
@andyblac I think so, but only with major releases that are in the release section / api listed. 

And then we have to determine the device type (1/2/PM/PlugS/...) so select the corresponding URL, fetch the hole update file and paste it to the /update function. 

Should be possible, but takes a little time ...

**Review by rojer — CHANGES_REQUESTED** [review]

**Comment by andyblac** [comment]
> @andyblac I think so, but only with major releases that are listed in the release section / api.
> 
> And then we have to determine the device type (1/2/PM/PlugS/...) so select the corresponding browser_download_url, fetch the hole update file and paste it to the /update function.
> 
> And we could switch between major-releases and testing-releases.
> 
> The function in this pull request is for "normal" users, so they could see if there is a major(stable)-release.
> 
> Should all be possible, but takes a little time ...

ye, major releases should be fine, we have my script for flashing test versions. regarding device type thats in `http://xxx.xxx.xxx.xxx/rpc/Shelly.GetInfo` under `app`
`{"id": "shelly1-F2824A", "app": "switch1", "model": "Shelly1", "host": "shelly1-F2824A.local",` that is tagged in GitHub downloads

**Comment by schemhad** [comment]
New PullRequest incoming, this time with more time, love and testing.

**Pull request closed without merging**
