### PR TITLE
[webui] buttons back to side by side, reduce page width, fix header.

### PR DESCRIPTION
**Pull request by andyblac**
here's what it looks like now
Screenshot 2021-02-16 at 11 11 26
Screenshot 2021-02-16 at 11 11 39

### CODE REVIEW

**Comment by andyblac** [comment]
should i centralise wifi button too ?

**Comment by andyblac** [comment]
latest version
Screenshot 2021-02-16 at 12 08 21

**Comment by andyblac** [comment]
Screenshot 2021-02-16 at 12 10 35

**Comment by andyblac** [comment]
not sure it failing checks??
```
  CXX    /home/runner/work/shelly-homekit/shelly-homekit/src/ADE7953/shelly_pm_ade7953.cpp
380
/home/runner/work/shelly-homekit/shelly-homekit/src/Shelly25/shelly_init_peripherals.cpp: In function 'mgos::Status shelly::PowerMeterInit(std::vector<std::unique_ptr<shelly::PowerMeter> >*)':
381
/home/runner/work/shelly-homekit/shelly-homekit/src/Shelly25/shelly_init_peripherals.cpp:31:36: error: variable 'const shelly::PowerMeterInit(std::vector<std::unique_ptr<shelly::PowerMeter> >*)::mgos_ade7953_config ade7953_cfg' has initializer but incomplete type
382
   31 |   const struct mgos_ade7953_config ade7953_cfg = {
383
      |                                    ^~~~~~~~~~~
384
/home/runner/work/shelly-homekit/shelly-homekit/deps/modules/mongoose-os/platforms/esp8266/Makefile.build:385: recipe for target '/home/runner/work/shelly-homekit/shelly-homekit/build_Shelly25/objs/shelly_init_peripherals.cpp.o' failed
385
make: *** [/home/runner/work/shelly-homekit/shelly-homekit/build_Shelly25/objs/shelly_init_peripherals.cpp.o] Error 1
386
make: *** Waiting for unfinished jobs....
387
make: Leaving directory '/app'
388
Makefile:76: recipe for target 'build-Shelly25' failed
389
make[1]: Leaving directory '/home/runner/work/shelly-homekit/shelly-homekit'
390
Makefile:32: recipe for target 'release' failed
391
Error: Process completed with exit code 2.
```

**Comment by rojer** [comment]
breaking changes to a library we depend on, i 'll fix it a bit later

**Comment by andyblac** [comment]
> breaking changes to a library we depend on, i 'll fix it a bit later

haha, thought wtf i have broke now!!

**Comment by andyblac** [comment]
this has not been tested on a phone, not sure what it will look like.

**Comment by andyblac** [comment]
ok hows this look guys
Screenshot 2021-02-16 at 15 10 33

**Comment by rojer** [comment]
looks good. this is phone, right? can you show desktop version too?

**Comment by andyblac** [comment]
> looks good. this is phone, right? can you show desktop version too?

ipad
mac
iphone8

**Comment by andyblac** [comment]
and iphone8
iphone8

**Comment by rojer** [comment]
LG

**Pull request merged**
