### PR TITLE
[Flashscript] more code optimisation.

### PR DESCRIPTION
**Pull request by andyblac**

### CODE REVIEW

**Comment by andyblac** [comment]
no good ?

**Comment by rojer** [comment]
um... you closed it, not me.

**Comment by andyblac** [comment]
hmm, strange

**Comment by andyblac** [comment]
i'll redo it.

**Comment by andyblac** [comment]
I just pushed anther commit, maybe because you pushed new commits and it got out of sync.

**Comment by rojer** [comment]
i guess you'll need to create another PR, branch for this one got deleted.

**Comment by andyblac** [comment]
yeah doing now.

**Pull request closed without merging**
