### PR TITLE
remove unused mqtt libs

### PR DESCRIPTION
**Pull request by timoschilling**
as far a I know this libs are unused.

### CODE REVIEW

**Comment by rojer** [comment]
keep it, it can be used for setting up remote RPC access.

**Comment by timoschilling** [comment]
RPC over mqtt via internet based server?

**Comment by rojer** [comment]
yes. once connected to server, a device can be reached via the same server like so:

mos --port=mqtt://SERVER/shellyswitch25-XXXXXX call Shelly.GetInfo

**Comment by rojer** [comment]
https://github.com/mongoose-os-libs/rpc-mqtt has the details

**Comment by timoschilling** [comment]
Thx

**Pull request closed without merging**
