### PR TITLE
add support for Shelly UNI

### LINKED ISSUE #479: Does this firmware work with shelly uni?
I want to make a temperature and humidity switch with two channels out of it.
Is it possible to make it homekit compatible?

### PR DESCRIPTION
**Pull request by timoschilling**
closes #479

basic uni support with:
- 2 switches
- 2 inputs
- GDO mode

features for a later PR:
- temp sensors
- ADC

### CODE REVIEW

**Comment by ChristophePretty** [comment]
Hi, 
FYI, I tested this integration on my Shelly UNI yesterday evening and everything looks good.

Thanks!

**Comment by rojer** [comment]
very nice, thank you!

**Comment by juanfal** [comment]
> 

I'd like to try it, but sorry, I don't know where to download the firmware from.

**Comment by 5xPa** [comment]
I would also like to try it, have 2 off UNI I would like to convert

**Comment by timoschilling** [comment]
It's not part of the beta1, @rojer can you release a beta2 please?

You can use the [flash script](https://github.com/mongoose-os-apps/shelly-homekit/wiki/Flashing#Script), with the following firmware file.
[shelly-homekit-ShellyUNI.zip](https://github.com/mongoose-os-apps/shelly-homekit/files/8169330/shelly-homekit-ShellyUNI.zip)

**Comment by timoschilling** [comment]
I have release a 2.11.0-beta2 build which contains support for the uni

**Comment by imeSven** [comment]
Hello. I'm trying to use the adc on the shelly uni homekit beta 3 but is not working I'm trying for 2 days now and I cannot figure it out yet 😔 can u please help me out? Thank you!

**Comment by timoschilling** [comment]
At the moment we only support the two inputs and two outputs. Not the adc and not the sensor input!

**Comment by imeSven** [comment]
Oh. If I only knew 😄 l. Sorry for that. 
Do you know when it will be avaliable or if is a "function" at this moment to make it work until the next update? Because I manage to use the shelly uni on an intercom and works flawless with homekit. I choosed the lock for the switch and is working instant with no issues. But I want to be notified when someone calls and I wanted to take the adc from the speakers. 
Thanks again and sorry for disturbing

**Comment by timoschilling** [comment]
We don’t have a route map

**Comment by imeSven** [comment]
Hello there. Any news about uni? Do u know if I can use adc for doorbell in uni to get signal and ring on my homepod?

**Comment by 5xPa** [comment]
There is a beta version which includes UNI. I have been running them successfully for quite sometime. I use them on relay outputs from Texecom alarm system. I run a shelly 1 as doorbell the Uni also includes options of doorbell
http://rojer.me/files/shelly/2.11.0-beta2/

**Comment by timoschilling** [comment]
@imeSven as I said, we don’t have a road map. Means maybe it comes in the next release, maybe it comes never.

**Comment by timoschilling** [comment]
This merge request of the initial implementation is a bad place for feature request or other discussions. That’s why I will lock it now. Feel free to open dedicated issues for that.

**Pull request merged**
