### PR TITLE
HomeKit label layout

### LINKED ISSUE #968: Homekit label layout
Hallo everybody from Italy,
I'm a newbie and not a programmer, but I really appreciate your works and this shelly-homekit firmware.
Everything is easy and work flowless, but I've a very little enanchment to suggest.
It is possible to change the QR homekit code layout to look like the orignal Apple one, as used in its HomeKit Accessory Simulator app?
I mean showing out in this way:
motion_qrcode

Because I use to print it on a label and stich it to the devices (like natively supported homekit devices).
thanks!

### PR DESCRIPTION
**Pull request by alexbartsch**
resolves #968

Here is how it looks like:
Bildschirmfoto 2022-03-31 um 16 48 43

### CODE REVIEW

**Comment by timoschilling** [comment]
@5xPa Wait for the next release

**Comment by 5xPa** [comment]
Ok thanks

**Comment by alexbartsch** [comment]
@timoschilling I don't understand the clang-format error, but I removed the whitespace changes on the `.cpp` files to see if this fixes it. Running `make check-format` is failing now on my machine. Is there any way my local clang is not doing the same as the clang in the github workflow?

**Comment by timoschilling** [comment]
There is a problem between the clang version on GitHub and your local version. Revert the cpp files back to what they are before your pr and it should be fine

**Comment by alexbartsch** [comment]
> There is a problem between the clang version on GitHub and your local version. Revert the cpp files back to what they are before your pr and it should be fine

@timoschilling Thanks for quick reply. I reverted the affected files.

**Comment by lalolerry** [comment]
Wow! Wonderful work @alexbartsch ! May thanks!

(maybe is better without code string in the bottom? Just asking)

I can't look forward to have it upgraded in the next release!

**Comment by kloibs** [comment]
> Wow! Wonderful work @alexbartsch ! Many Many thanks!
> 
> maybe is better without Honekit code string in the bottom? Just asking
> 
> And is possible to add a "save label as" (.jpg) button?
> 
> I can't look forward to have it upgraded in the next release!

First of all, thank you @alexbartsch and @timoschilling for your awesome work! 

@lalolerry I understand your goal with this HomeKit code and I appreciate it. But isn’t this successful enough? Just take a screenshot and save it as a .jpeg. End of story ( ͡° ͜ʖ ͡°)

**Comment by lalolerry** [comment]
@kloibs Yes I konw and yes very successful! but you know... my lazyness...  ^_^'

@alexbartsch: and maybe is possible to add also a "show again" button? To save it or print also later :)

**Comment by alexbartsch** [comment]
@lalolerry first things first. 😉 

@timoschilling would you mind approving again?

**Comment by alexbartsch** [comment]
@lalolerry first things first. 😉 

@timoschilling would you mind approving again?

**Comment by timoschilling** [comment]
for easier review white space can be ignored https://github.com/mongoose-os-apps/shelly-homekit/pull/973/files?diff=split&w=1

**Comment by rojer** [comment]
it's great to see it done, thanks everyone!

however, as a point of style: please refrain from mixing large reformatting with substantial changes, it's hard to see what actually changed.

**Comment by timoschilling** [comment]
@rojer  I agree with you, but it was just a whitespace change. GitHub can ignore whitespace changes. Use the link in my last comment and you can see the real changes

**Comment by lalolerry** [comment]
Uhm, I just found a intresting link Apple Develper site about Homekit icon and label design Guidelines:

https://developer.apple.com/design/human-interface-guidelines/homekit/overview/icons/

**Pull request merged**
