### PR TITLE
Link update alert to the system update section (Fix #303)

### LINKED ISSUE #303: Make the Update Alert a link to the System.Update section
Today I clicked the **Update** Alert icon on the top of the Shelly1 internal webpage expecting it to be a button and it to start the update process or take me to the update section.

It doesn’t.

But then I thought: it looks like a button and I clicked it because I though it was a button.

So why not make it a button, or a clickable link to take you to the Update line in the System section?
That should be easily doable with relative URL linking within the same page...

### PR DESCRIPTION
**Pull request by ZeevoX**
* use `div`'s `onclick` to teleport user to correct section
* style the mouse pointer so that it is clear that it is clickable

Screenshot from 2021-01-20 19-24-28

### CODE REVIEW

**Comment by rojer** [comment]
instead of this, can we make badges <a>s instead of <div>s? this way we can use a's href attribute.

**Comment by ZeevoX** [comment]
sorry, I don't understand what you mean by s

**Comment by rojer** [comment]
oh, github butchered the html tags in the comment. fixed.

**Comment by andyblac** [comment]
linked to issue https://github.com/mongoose-os-apps/shelly-homekit/issues/303

**Comment by ZeevoX** [comment]
image

re-did it using `<a>` tags. also stopped badges overlaying on top of each other if shown simultaneously.

**Comment by rojer** [comment]
nice! please rebase and it's good to go

**Comment by rojer** [comment]
thank you!

**Pull request merged**
