### PR TITLE
Auto off delay support for down to 10ms.

### LINKED ISSUE #53: “Auto off” functionality in mili-seconds....
Hello Folks,

The 1.8 release is awesome! Thanks a lot ;o)
I face a specific application that would require pulses in mili-seconds.....
The regular Shelly firmware can be set up this way. Any chance that the next release could consider a format: like: 00:00:00:01 or 00:00:00:05 ?

Thanks for your support in advance,
Flying150!

### PR DESCRIPTION
**Pull request by handy-manny-swe**
Fixes #53 .

Marked as draft as it needs some more testing.

### CODE REVIEW

**Comment by rojer** [comment]
I suggest the following pattern: `HH:MM:SS.sss`, `sss` being the millisecond part.
we won't be able to support low fractional parts but it will be more familiar, having just 2 digits is confusing.

**Comment by handy-manny-swe** [comment]
> I suggest the following pattern: `HH:MM:SS.sss`, `sss` being the millisecond part.
> we won't be able to support low fractional parts but it will be more familiar, having just 2 digits is confusing.

I thought about that as well, but I personally find it more confusing to invite the user to type values that we don't support.

**Comment by rojer** [comment]
there's that, but it's just not intuitive if you have just 2 digits. if it's 3, you realize it's milliseconds immediately. lower digit won't be meaningful, but for presentation sake let's have 3.

**Comment by handy-manny-swe** [comment]
> there's that, but it's just not intuitive if you have just 2 digits. if it's 3, you realize it's milliseconds immediately. lower digit won't be meaningful, but for presentation sake let's have 3.

Well, it's only milliseconds in code. That does not necessarily need to be reflected in the UI as we could as well call it hundredths of second. But we'll go with 3 and make some kind of effort to not trick the user into typing values less than 10ms.

**Comment by andyblac** [comment]
@handy-manny-swe or just code it so anything less than 10ms is actioned as 10ms

**Comment by handy-manny-swe** [comment]
> @handy-manny-swe or just code it so anything less than 10ms is actioned as 10ms
> 
> and display a note on screen say so.

I'm leaning towards validation and validation message. At least that's what I've just coded. :)

**Comment by andyblac** [comment]
i wish i knew C so i could help you guys 😄

**Comment by handy-manny-swe** [comment]
Seems to work. My one and only shelly1 is installed in my garage door electronics box, so my testing possibilities are a bit limited. But a setting of 10ms sure triggers a lot faster than a setting of 1s.

**Comment by rojer** [comment]
merged, with some minor modifications

**Pull request closed without merging**
