### PR TITLE
[FlashScript] add script mode:  -m {homekit | revert | keep}

### PR DESCRIPTION
**Pull request by andyblac**

### CODE REVIEW

**Comment by andyblac** [comment]
for some reason getting official to update firmware fails even though flashing from official to home works, and should be the exact same command.

flashing to HomeKit from Official
```
macbookpro:tools andrewblackburn$ ./flash_shelly.sh shelly1-F2824A.local
Host: shelly1-F2824A.local
Model: Shelly1
Current: Official 1.8.0
Latest: HomeKit 2.0.12
DURL: http://rojer.me/files/shelly/2.0.12/shelly-homekit-Shelly1.zip
Do you wish to flash shelly1-F2824A.local to firmware version 2.0.12 ? y
Now Flashing..
{"status":"updating","has_update":false,"new_version":"20200812-090904/v1.8.0@8acf41b0","old_version":"20200812-090904/v1.8.0@8acf41b0"}
waiting for shelly1-F2824A.local to reboot
still waiting for shelly1-F2824A.local to reboot
Successfully flashed shelly1-F2824A.local to 2.0.12
```

trying to update official
```
macbookpro:tools andrewblackburn$ ./flash_shelly.sh -m keep shellyrgbw2-B075D3.local
Host: shellyrgbw2-B075D3.local
Model: SHRGBW2
Current: Official 1.7.3
Latest: Official 1.8.2
DURL: http://api.shelly.cloud/firmware/SHRGBW2.zip
Do you wish to flash shellyrgbw2-B075D3.local to firmware version 1.8.2 ? y
Now Flashing..
{"status":"updating","has_update":false,"new_version":"20200818-120558/v1.8.2@36539b0b","old_version":"20200625-102512/v1.7.3@2aa0993a"}
waiting for shellyrgbw2-B075D3.local to reboot
still waiting for shellyrgbw2-B075D3.local to reboot
Flash failed!!!
```

**Comment by andyblac** [comment]
strange it worked for my dimmer, but not working for my RGBW2's ??? hmm

```
Host: shellydimmer-F3CD89.local
Model: SHDM-1
Current: Official 1.7.0
Latest: Official 1.8.0
DURL: http://api.shelly.cloud/firmware/SHDM-1.zip
Do you wish to flash shellydimmer-F3CD89.local to firmware version 1.8.0 ? y
Now Flashing..
{"status":"updating","has_update":false,"new_version":"20200717-113325/v1.7.7@a02db0b8","old_version":"20200601-123355/v1.7.0@d7961837"}
waiting for shellydimmer-F3CD89.local to reboot
still waiting for shellydimmer-F3CD89.local to reboot
Successfully flashed shellydimmer-F3CD89.local to 1.8.0
```

**Comment by rojer** [comment]
so, can this be merged or would you like to continue working on it? changes seem fine to me.

**Comment by andyblac** [comment]
Yeah can be merged code is correct as you can flash back and forth from official to yours

**Comment by rojer** [comment]
merged, thank you!

**Comment by andyblac** [comment]
Np let me Know if you want anything else adding to it

**Comment by andyblac** [comment]
@rojer can you add the official shelly model name to a field in `Shelly.GetInfo` this way any new device that comes out we won't have to update the script to support reverting.

**Comment by andyblac** [comment]
just to let you know, I found the issue with updating stock firmware on RGBW2, it appears it requires a mode change RGB to WHITE mode and BACK, as the stock firmware contains 2 firmwares. once you switch modes it shows correct FW version, so I will add a message asking user to switch modes to finalise flash process.

unless I can find the API for switching modes. then I could try to code script to do it automatically.

**Comment by andyblac** [comment]
how dose this sound

```
          echo "To finalise flash process you will need to switch 'Modes' in device WebUI,"
          echo "Goto http://$device in your web browser"
          echo "Goto settings section"
          echo "Goto 'Device Type' and switch modes"
          echo "Once mode has been changed, you can switch it back to your preferred mode."
```

**Comment by andyblac** [comment]
switching modes automatically imo is a no go, as if your using the device with Homebridge, it make HomeKit loose all scenes / automations you have assigned to that device.

so think it is best to stick with the message for now, I have submitted a support ticket with Shelly regarding this issue let see what they say.

**Comment by andyblac** [comment]
```
          echo "To finalise flash process you will need to switch 'Modes' in device WebUI,"
          echo "WARNING!! If you are using this device in conjuction with Homebridge it wiil"
          echo "result in ALL scenes / automations to be removed within HomeKit."
          echo "Goto http://$device in your web browser"
          echo "Goto settings section"
          echo "Goto 'Device Type' and switch modes"
          echo "Once mode has been changed, you can switch it back to your preferred mode."
```

**Comment by rojer** [comment]
seems reasonable. it's definitely an interesting finding.

**Pull request merged**
